# Generated by Django 4.0.2 on 2022-02-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_usermodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
