# Generated by Django 4.0.2 on 2022-02-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_usermodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='This is a default Photo', upload_to=''),
        ),
    ]
